
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: azuremachinepools.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: AzureMachinePool
    plural: azuremachinepools
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AzureMachinePool is the Schema for the azuremachinepools API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AzureMachinePoolSpec defines the desired state of AzureMachinePool
          properties:
            name:
              description: Name
              type: string
            providerID:
              description: ProviderID is the unique identifier as specified by the
                cloud provider.
              type: string
            resourceGroup:
              description: ResourceGroup
              properties:
                name:
                  description: Name
                  type: string
                region:
                  description: Region
                  type: string
                subscriptionID:
                  description: SubscriptionID
                  type: string
              type: object
            sku:
              description: SKU
              type: string
            sshPublicKey:
              description: SSHPublicKey
              type: string
            subnet:
              description: Subnet
              type: string
          type: object
        status:
          description: AzureMachinePoolStatus defines the observed state of AzureMachinePool
          properties:
            errorMessage:
              description: Any transient errors that occur during the reconciliation
                of Machines can be added as events to the Machine object and/or logged
                in the controller's output.
              type: string
            errorReason:
              description: Any transient errors that occur during the reconciliation
                of Machines can be added as events to the Machine object and/or logged
                in the controller's output.
              type: string
            ready:
              description: Ready is true when the provider resource is ready.
              type: boolean
            replicas:
              description: Replicas is the most recently observed number of replicas.
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
